# Generated by Django 3.0.7 on 2021-01-15 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0002_auto_20210113_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='hybrid_uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
