# Generated by Django 3.0.7 on 2021-01-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0006_remove_userdetail_hybrid_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='hybrid_uid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
